version: "3"
services:
  app:
    image: sswedding
    ports:
      - 4000:4000
    environment:
      SECRET_KEY_BASE: xgfCh7KtpUDOwH/laQLkfBkMyDhZ7Q+ZDewle59tVMOvqTs4L4cLBQNbOCqKsnzK
      DATABASE_PATH: /mnt/sswedding.db
    # volumes:
    #   - ./core_dev.db:/mnt/sswedding.db
