import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :guest_portal, GuestPortal.Endpoint, url: [host: "sswedding.srallops.com", port: 443]
